; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
board = esp32dev
platform =  espressif32
framework = 
	arduino
lib_deps = https://github.com/KillerInk/DFRobot_GP8403.git
            https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.7.0
            https://github.com/ESP32Async/AsyncTCP.git#v3.3.5
            https://github.com/arduino-libraries/Arduino_JSON.git
            https://github.com/h2zero/NimBLE-Arduino.git
            https://github.com/DFRobot/DFRobot_ENS160
            https://github.com/finitespace/BME280.git
	        https://github.com/dvarrel/AHT20.git
board_build.partitions = custom_partition.csv
build_flags = -DCORE_DEBUG_LEVEL=5
              -DCONFIG_NIMBLE_CPP_LOG_LEVEL=0
              ;-DUSE_SDCARD=1    ;enable for sdcard logging
              -DSENSOR_ENS160AHT21=1 ;enable when using a ENS160AHT21 sensor
              -Di2c_aht_addr=56 ;aht i2c adress enable when using -DSENSOR_ENS160AHT21
              -Di2c_ens_add=83  ;ens i2c adress enable when using -DSENSOR_ENS160AHT21
              ;-DSENSOR_BME280=1 ;enable when using bme280 sensor
              ;-DBME_I2C_ADD=119 ;enable when using -DSENSOR_BME280
              -DI2C_SDA=21 ;ic2 sda pin
              -DI2C_SCL=22 ;ic2 scl pin
              -Di2c_pwn_addr=95 ;fan pwm i2c address
              -Di2c_light_addr=94   ;light pwm i2c adress
              -Dtime_zone_hour_utc_offset=1
              -DMYSSID=\"GrowFanController\"
              -DPW=\"pw\"
              -Dhttp_port=80
;build_unflags = -Werror=all.

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
board_build.arduino.upstream_packages = no
extra_scripts = build:ngbuild.py

